In [ ]:
# Q1 欠損値の確認（df1を使用）
# データ: /mnt/data/20250817_df1.csv を読み込み、列ごとの欠損値の個数を表示してください。
# 期待：各列の NaN 個数が Series で出力されること
import pandas as pd
df = pd.read_csv("20250817_df1.csv")
# ここに解答
df_nan = df.isna().sum()

print(df_nan)

<class 'pandas.core.series.Series'>

In [13]:
# Q2 欠損の削除（列/行）（df1を使用）
# データ: /mnt/data/20250817_df1.csv
# (1) 全て NaN の列があれば削除（なければ何も起きない）
# (2) score 列が NaN の行を削除
# それぞれの結果の shape を確認してください。
import pandas as pd
df = pd.read_csv("20250817_df1.csv")
# ここに解答
print(df.shape)
test_df1 = df.dropna(how="all")
print(test_df1.shape)
test_df2 = df.dropna(subset="score")
print(test_df2.shape)

(11, 7)
(11, 7)
(9, 7)

In [ ]:
# Q3 欠損の補完（単一値）（salesを使用）
# データ: /mnt/data/20250817_sales.csv
# qty 列の欠損を 0 で埋めて、埋めた後の欠損数を確認してください。
import pandas as pd
df = pd.read_csv('20250817_sales.csv', parse_dates=['date'])
# ここに解答
print(df["qty"].isna().sum())

df["qty"] = df["qty"].fillna(0)

print(df["qty"].isna().sum())

2
0

In [18]:
# Q4 欠損の中央値補完（df1を使用）
# データ: /mnt/data/20250817_df1.csv
# score 列の欠損を「中央値」で補完し、補完前後の score の要約統計量（describe）を比較してください。
import pandas as pd
import numpy as np
df = pd.read_csv('20250817_df1.csv')
# ここに解答
print(df["score"].describe())

df["score"] = df["score"].fillna(df["score"].median())

print(df["score"].describe())

count     9.000000
mean     72.888889
std      11.005049
min      58.000000
25%      66.000000
50%      75.000000
75%      81.000000
max      90.000000
Name: score, dtype: float64
count    11.000000
mean     73.272727
std       9.880191
min      58.000000
25%      67.500000
50%      75.000000
75%      79.000000
max      90.000000
Name: score, dtype: float64

In [19]:
# Q5 重複の検出と削除（df1を使用）
# データ: /mnt/data/20250817_df1.csv
# 完全重複行の件数を確認し、重複を削除してから行数の変化を表示してください。
import pandas as pd
df = pd.read_csv('20250817_df1.csv')
# ここに解答
print(df)

df = df.drop_duplicates()

print(df)

    id  gender status  height_cm  weight_kg  score city
0    1       1     出席      170.0       65.0   82.0   東京
1    2       2     欠席      160.0        NaN   75.0   大阪
2    3       1     出席        NaN       80.0   90.0  名古屋
3    4       2    NaN      155.0       54.0    NaN   東京
4    5       1     出席      180.0       90.0   58.0   大阪
5    6       2     欠席      165.0       48.0   66.0   不明
6    7       1     出席      172.0        NaN   77.0   東京
7    8       2     出席      158.0       52.0   81.0   大阪
8    9       1     欠席        NaN        NaN    NaN  名古屋
9   10       2     出席      162.0       50.0   69.0   東京
10   5       1     出席      180.0       90.0   58.0   大阪
   id  gender status  height_cm  weight_kg  score city
0   1       1     出席      170.0       65.0   82.0   東京
1   2       2     欠席      160.0        NaN   75.0   大阪
2   3       1     出席        NaN       80.0   90.0  名古屋
3   4       2    NaN      155.0       54.0    NaN   東京
4   5       1     出席      180.0       90.0   58.0   大阪
5   6       2     欠席      165.0       48.0   66.0   不明
6   7       1     出席      172.0        NaN   77.0   東京
7   8       2     出席      158.0       52.0   81.0   大阪
8   9       1     欠席        NaN        NaN    NaN  名古屋
9  10       2     出席      162.0       50.0   69.0   東京

In [ ]:
# Q6 値の置換（replace）（df1を使用）
# データ: /mnt/data/20250817_df1.csv
# status 列で「出席」を 1、「欠席」を 0 に置換した新しい列 status_bin を作成してください（None はそのまま）。
import pandas as pd
df = pd.read_csv('20250817_df1.csv')
# ここに解答

print(df)

df["status_bin"] = df["status"].replace({"出席":1,"欠席":0})

pd.set_option('future.no_silent_downcasting', True)

print(df)

    id  gender status  height_cm  weight_kg  score city
0    1       1     出席      170.0       65.0   82.0   東京
1    2       2     欠席      160.0        NaN   75.0   大阪
2    3       1     出席        NaN       80.0   90.0  名古屋
3    4       2    NaN      155.0       54.0    NaN   東京
4    5       1     出席      180.0       90.0   58.0   大阪
5    6       2     欠席      165.0       48.0   66.0   不明
6    7       1     出席      172.0        NaN   77.0   東京
7    8       2     出席      158.0       52.0   81.0   大阪
8    9       1     欠席        NaN        NaN    NaN  名古屋
9   10       2     出席      162.0       50.0   69.0   東京
10   5       1     出席      180.0       90.0   58.0   大阪

    id  gender status  height_cm  weight_kg  score city status_bin
0    1       1     出席      170.0       65.0   82.0   東京          1
1    2       2     欠席      160.0        NaN   75.0   大阪          0
2    3       1     出席        NaN       80.0   90.0  名古屋          1
3    4       2    NaN      155.0       54.0    NaN   東京        NaN
4    5       1     出席      180.0       90.0   58.0   大阪          1
5    6       2     欠席      165.0       48.0   66.0   不明          0
6    7       1     出席      172.0        NaN   77.0   東京          1
7    8       2     出席      158.0       52.0   81.0   大阪          1
8    9       1     欠席        NaN        NaN    NaN  名古屋          0
9   10       2     出席      162.0       50.0   69.0   東京          1
10   5       1     出席      180.0       90.0   58.0   大阪          1

In [29]:
# Q7 カテゴリのマッピング（map）（df1を使用）
# データ: /mnt/data/20250817_df1.csv
# gender 列（1,2）を map で「男」「女」に変換した新しい列 gender_str を作成してください（欠損はそのまま）。
import pandas as pd
df = pd.read_csv('20250817_df1.csv')
# ここに解答
map_list = {1:"男",2:"女"}

df["gender_str"] = df["gender"].map(map_list)

df

    id  gender status  height_cm  weight_kg  score city gender_str
0    1       1     出席      170.0       65.0   82.0   東京          男
1    2       2     欠席      160.0        NaN   75.0   大阪          女
2    3       1     出席        NaN       80.0   90.0  名古屋          男
3    4       2    NaN      155.0       54.0    NaN   東京          女
4    5       1     出席      180.0       90.0   58.0   大阪          男
5    6       2     欠席      165.0       48.0   66.0   不明          女
6    7       1     出席      172.0        NaN   77.0   東京          男
7    8       2     出席      158.0       52.0   81.0   大阪          女
8    9       1     欠席        NaN        NaN    NaN  名古屋          男
9   10       2     出席      162.0       50.0   69.0   東京          女
10   5       1     出席      180.0       90.0   58.0   大阪          男

In [64]:
# Q8 applyで派生列作成（df1を使用）
# データ: /mnt/data/20250817_df1.csv
# height_cm, weight_kg から BMI（kg/m^2）を計算して列 bmi を作成し、
# さらに bmi を基に「<18.5: 'Under', 18.5-25: 'Normal', >=25: 'Over'」のクラス列 bmi_cls を作成してください。
import pandas as pd
import numpy as np
df = pd.read_csv('20250817_df1.csv')
# ここに解答
#身長と体重がNaNの場合は中央値を入れる
df["height_cm"] = df["height_cm"].fillna(df["height_cm"].median())
df["weight_kg"] = df["weight_kg"].fillna(df["weight_kg"].median())

df["bmi"] = df.apply(lambda x:x["weight_kg"] / (x["height_cm"]*2)*100,axis=1)


#df["bmi"] = df["weight_kg"]/(df["height_cm"] * 2)*100
#print(df)

bins = [0,18.5,25,100]
group_names = ["Under","Normal","Over"]
bmi_cut = pd.cut(df["bmi"],bins, labels=group_names,right=False)
#print(bmi_cut)
df["bmi_cls"] = bmi_cut


print(df)

    id  gender status  height_cm  weight_kg  score city        bmi bmi_cls
0    1       1     出席      170.0       65.0   82.0   東京  19.117647  Normal
1    2       2     欠席      160.0       59.5   75.0   大阪  18.593750  Normal
2    3       1     出席      165.0       80.0   90.0  名古屋  24.242424  Normal
3    4       2    NaN      155.0       54.0    NaN   東京  17.419355   Under
4    5       1     出席      180.0       90.0   58.0   大阪  25.000000    Over
5    6       2     欠席      165.0       48.0   66.0   不明  14.545455   Under
6    7       1     出席      172.0       59.5   77.0   東京  17.296512   Under
7    8       2     出席      158.0       52.0   81.0   大阪  16.455696   Under
8    9       1     欠席      165.0       59.5    NaN  名古屋  18.030303   Under
9   10       2     出席      162.0       50.0   69.0   東京  15.432099   Under
10   5       1     出席      180.0       90.0   58.0   大阪  25.000000    Over

In [92]:
# Q9 クリーニング規則の適用（salesを使用）
# データ: /mnt/data/20250817_sales.csv
# 以下のクリーニングを行い、クレンジング後の件数と合計売上(qty*price)を確認してください。
# 1) qty < 0 を 0 にクリップする
# 2) price <= 0 または price が欠損の行を除去
# 3) qty の欠損は 0 補完
# 4) 型を qty=int, price=float に整える
import pandas as pd
df = pd.read_csv('20250817_sales.csv', parse_dates=['date'])
# ここに解答


df["qty"] = df["qty"].fillna(0)
df["qty"] = df["qty"].clip(lower=0)

df[df["price"] <= 0] = np.nan
df = df.dropna(subset="price")

df["qty"] = pd.to_numeric(df["qty"], errors="coerce").astype(int)
df["price"] = pd.to_numeric(df["price"], errors="coerce").astype(float)

print(df)

   store product  qty  price       date notes
0    東京店       A   10  120.0 2025-07-01   NaN
1    大阪店       B    0  200.0 2025-07-02   NaN
2   名古屋店       C    0  150.0 2025-07-03    返品
4    大阪店       D    8  300.0 2025-07-05   NaN
5   名古屋店       B   15  180.0 2025-07-06   NaN
6    東京店       C    0  220.0 2025-07-07   NaN
7    大阪店       A   20  100.0 2025-07-08   セール
9    東京店       B    3  200.0 2025-07-10   NaN
10   大阪店       C   12  190.0 2025-07-11   NaN
11  名古屋店       A    9  110.0 2025-07-12   NaN

In [105]:
# Q10 インデックス操作（salesを使用）
# データ: /mnt/data/20250817_sales.csv
# store と date の複合インデックスに設定→日付昇順に並べ替え→最後に reset_index() で戻してください。
import pandas as pd
df = pd.read_csv('20250817_sales.csv', parse_dates=['date'])
# ここに解答
print(df)
df = df.set_index(["store","date"])
df = df.sort_index(level="date")
df = df.reset_index()

print(df)

   store product   qty  price       date  notes
0    東京店       A  10.0  120.0 2025-07-01    NaN
1    大阪店       B   NaN  200.0 2025-07-02    NaN
2   名古屋店       C  -3.0  150.0 2025-07-03     返品
3    東京店       A   5.0    0.0 2025-07-04  単価未設定
4    大阪店       D   8.0  300.0 2025-07-05    NaN
5   名古屋店       B  15.0  180.0 2025-07-06    NaN
6    東京店       C   NaN  220.0 2025-07-07    NaN
7    大阪店       A  20.0  100.0 2025-07-08    セール
8   名古屋店       D   7.0    NaN 2025-07-09    NaN
9    東京店       B   3.0  200.0 2025-07-10    NaN
10   大阪店       C  12.0  190.0 2025-07-11    NaN
11  名古屋店       A   9.0  110.0 2025-07-12    NaN
   store       date product   qty  price  notes
0    東京店 2025-07-01       A  10.0  120.0    NaN
1    大阪店 2025-07-02       B   NaN  200.0    NaN
2   名古屋店 2025-07-03       C  -3.0  150.0     返品
3    東京店 2025-07-04       A   5.0    0.0  単価未設定
4    大阪店 2025-07-05       D   8.0  300.0    NaN
5   名古屋店 2025-07-06       B  15.0  180.0    NaN
6    東京店 2025-07-07       C   NaN  220.0    NaN
7    大阪店 2025-07-08       A  20.0  100.0    セール
8   名古屋店 2025-07-09       D   7.0    NaN    NaN
9    東京店 2025-07-10       B   3.0  200.0    NaN
10   大阪店 2025-07-11       C  12.0  190.0    NaN
11  名古屋店 2025-07-12       A   9.0  110.0    NaN